name: Arch Linux Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Update packages and install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed --overwrite '*' \
            openssh sudo \
            git fakeroot binutils gcc awk binutils xz \
            libarchive bzip2 coreutils file findutils \
            gettext grep gzip sed ncurses util-linux \
            pacman-contrib debugedit
      - uses: actions/checkout@v3
      - name: Create non-root user
        run: |
          chmod +x .github/workflows/setup-builder.sh
          ./.github/workflows/setup-builder.sh
      - name: Build package as non-root user
        run: |
          chmod +x .github/workflows/build.sh
          runuser builder --command 'bash -l -c .github/workflows/build.sh'
