name: Arch Linux Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
      - name: Update packages and install dependencies
        run: |
          pacman -Sy --noconfirm
          pacman -Syu --noconfirm base-devel git
      - uses: actions/checkout@v3
      - run: makepkg -si --noconfirm
